-- =============================================================
-- Reference data: schemes, eligibility rules, institutions,
-- integration registry, knowledge base, scripted mock overrides
-- Figures traced to MoTA / NSP sources (see source_url).
-- =============================================================

insert into public.schemes
  (code, name, short_name, portal, portal_url, level, is_central_sector, funding_pattern,
   income_ceiling, slots_per_year, benefit, eligibility_summary, document_requirements,
   deadline_fresh, deadline_renewal, source_url, figures_verified_on, accent, sort_order)
values
  ('pre_matric',
   'Pre-Matric Scholarship for ST Students',
   'Pre-Matric',
   'NSP', 'https://scholarships.gov.in',
   'Secondary · Class IX–X',
   false,
   'Centrally Sponsored: 75:25 (90:10 NE/Hill states, 100:0 UTs without legislature)',
   250000, null,
   '{"dayScholarPerMonth":225,"hostellerPerMonth":525,"monthsPerYear":10,
     "note":"Ten months per academic year, paid via PFMS-DBT into Aadhaar-seeded account."}'::jsonb,
   'Student must be studying in Class IX or X and parental income from all sources must not exceed Rs. 2.50 lakh per annum.',
   '[{"docType":"st_certificate","label":"ST / PVTG certificate","mandatory":true},
     {"docType":"income_certificate","label":"Income certificate","mandatory":true},
     {"docType":"domicile","label":"Domicile certificate","mandatory":true},
     {"docType":"aadhaar","label":"Aadhaar","mandatory":true},
     {"docType":"institution_bonafide","label":"Institution bonafide","mandatory":true},
     {"docType":"bank_passbook","label":"Bank passbook (Aadhaar seeded)","mandatory":true}]'::jsonb,
   '2026-11-30', '2027-02-28',
   'https://tribal.nic.in/Scholarship.aspx', '2026-09-26', '#0F766E', 1),

  ('post_matric',
   'Post-Matric Scholarship for ST Students',
   'Post-Matric',
   'NSP', 'https://scholarships.gov.in',
   'Senior Secondary & above · Class XI+',
   false,
   'Centrally Sponsored: 75:25 (90:10 NE/Hill states, 100:0 UTs without legislature)',
   250000, null,
   '{"tuitionFee":"Full non-refundable fees reimbursed",
     "maintenanceAllowance":"As per group / stream notified by the State",
     "note":"Two components: fee reimbursement + maintenance allowance."}'::jsonb,
   'Student must be pursuing a recognised course after Class X and parental income from all sources must not exceed Rs. 2.50 lakh per annum.',
   '[{"docType":"st_certificate","label":"ST / PVTG certificate","mandatory":true},
     {"docType":"income_certificate","label":"Income certificate","mandatory":true},
     {"docType":"domicile","label":"Domicile certificate","mandatory":true},
     {"docType":"aadhaar","label":"Aadhaar","mandatory":true},
     {"docType":"marksheet","label":"Previous marksheet","mandatory":true},
     {"docType":"institution_bonafide","label":"Institution bonafide","mandatory":true},
     {"docType":"bank_passbook","label":"Bank passbook (Aadhaar seeded)","mandatory":true}]'::jsonb,
   '2026-11-30', '2027-02-28',
   'https://tribal.nic.in/Scholarship.aspx', '2026-09-26', '#1D4ED8', 2),

  ('top_class',
   'National Scholarship for Higher Education of ST Students (Top Class)',
   'Top Class',
   'NSP', 'https://tribal.nic.in/Scholarship.aspx',
   'Graduation & Post-Graduation · notified institutes',
   true, '100% Central funding',
   600000, 1000,
   '{"tuitionFeeCeiling":250000,
     "booksAndStationeryPerYear":5000,
     "stipendPerMonth":3000,
     "computerOneTime":45000,
     "paymentSplit":"Component I (stipend, books, computer, non-refundable fees) to student via PFMS-DBT; Component II (tuition + admission fee) to the Institute via PFMS.",
     "privateInstituteCeilingPerYear":250000}'::jsonb,
   'Meritorious ST student admitted to a full-time notified Top Class Institute; family income from all sources must not exceed Rs. 6.00 lakh per annum. Scholarship continues for the full course duration.',
   '[{"docType":"st_certificate","label":"ST / PVTG certificate","mandatory":true},
     {"docType":"income_certificate","label":"Income certificate","mandatory":true},
     {"docType":"aadhaar","label":"Aadhaar","mandatory":true},
     {"docType":"marksheet","label":"Class XII marksheet","mandatory":true},
     {"docType":"institution_bonafide","label":"Institute admission letter","mandatory":true},
     {"docType":"bank_passbook","label":"Bank passbook (Aadhaar seeded)","mandatory":true}]'::jsonb,
   '2026-10-31', '2027-01-31',
   'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf',
   '2026-09-26', '#7C3AED', 3),

  ('nfst',
   'National Fellowship for Higher Education of ST Students (NFST)',
   'NFST Fellowship',
   'SFMP', 'https://scholarship.canarabank.in',
   'M.Phil / M.Phil+Ph.D / Ph.D · research fellowship',
   true, '100% Central funding',
   null, 750,
   '{"mPhilStipendPerMonth":31000,
     "phdStipendPerMonthFirstTwoYears":31000,
     "phdStipendPerMonthRemaining":35000,
     "contingencyHumanitiesSocialSciences":10000,
     "contingencyScienceEngineeringTechnology":12000,
     "contingencyPhdHumanitiesSocialSciences":20500,
     "contingencyPhdScienceEngineeringTechnology":25000,
     "hra":"At par with UGC rates (8% / 16% / 24% by city)",
     "escortAllowance":2000,
     "disbursal":"Quarterly through PFMS-DBT into the scholar Aadhaar-seeded bank account",
     "priorityOrder":"PVTG first, then female candidates, then BPL, then inter-se merit"}'::jsonb,
   'ST student who has passed the Post-Graduation examination and is admitted to a regular, full-time M.Phil / Ph.D in a UGC-entitled or Government-funded institution. Not eligible for any other fellowship for the same study. No State or University-wise ceiling.',
   '[{"docType":"st_certificate","label":"ST / PVTG certificate","mandatory":true},
     {"docType":"aadhaar","label":"Aadhaar","mandatory":true},
     {"docType":"marksheet","label":"Post-graduation marksheet","mandatory":true},
     {"docType":"institution_bonafide","label":"Institute / guide confirmation","mandatory":true},
     {"docType":"bank_passbook","label":"Bank passbook (Aadhaar seeded)","mandatory":true},
     {"docType":"net_jrf","label":"NET / JRF (if claimed)","mandatory":false}]'::jsonb,
   '2026-10-31', '2027-01-31',
   'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf',
   '2026-09-26', '#B45309', 4),

  ('nos',
   'National Overseas Scholarship for ST Students',
   'NOS (Overseas)',
   'NOS', 'https://nos.mota.gov.in',
   'Studies abroad · top 1000 QS-ranked universities',
   true, '100% Central funding',
   600000, 20,
   '{"slotsPerYear":20,
     "ageLimit":{"masters":32,"phd":35,"postDoctoral":38},
     "universityCriterion":"Top 1000 universities as per latest QS World University Rankings",
     "covers":"Tuition, travel, living allowance and contingency as per MoTA NOS guidelines"}'::jsonb,
   'ST student whose family income does not exceed Rs. 6.00 lakh per annum, seeking admission to a top 1000 QS-ranked university abroad. Age limit: 32 for Master''s, 35 for Ph.D and 38 for post-doctoral research.',
   '[{"docType":"st_certificate","label":"ST / PVTG certificate","mandatory":true},
     {"docType":"income_certificate","label":"Income certificate","mandatory":true},
     {"docType":"aadhaar","label":"Aadhaar","mandatory":true},
     {"docType":"marksheet","label":"Academic transcripts","mandatory":true},
     {"docType":"passport","label":"Valid passport","mandatory":true},
     {"docType":"nos_offer_letter","label":"University offer letter","mandatory":true},
     {"docType":"nos_qs_proof","label":"QS ranking evidence","mandatory":true},
     {"docType":"bank_passbook","label":"Bank passbook","mandatory":true}]'::jsonb,
   '2026-09-30', null,
   'https://tribal.nic.in/Scholarship.aspx', '2026-09-26', '#BE123C', 5);

-- ---------- eligibility rules (engine reads these, nothing hard-coded) ----------
insert into public.scheme_rules
  (scheme_code, rule_key, rule_type, params, severity, label_en, label_hi, source_url)
values
  ('pre_matric','income_2_5lakh','income_ceiling', '{"maxAnnual":250000}', 'blocker',
   'Family income must not exceed Rs. 2.50 lakh per annum',
   'पारिवारिक आय वार्षिक Rs. 2.50 लाख से अधिक नहीं होनी चाहिए',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('pre_matric','class_ix_x','class_level', '{"min":"IX","max":"X"}', 'blocker',
   'Student must be in Class IX or X on a full-time basis',
   'छात्र कक्षा IX या X में नियमित अध्ययन कर रहा हो',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('pre_matric','domicile_required','domicile', '{}', 'blocker',
   'Domicile certificate of the State / UT is required','आवासीय प्रमाण पत्र आवश्यक',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('pre_matric','one_scheme_at_a_time','single_scheme', '{}', 'blocker',
   'A student may hold only one scholarship at a time','एक समय में केवल एक छात्रवृत्ति',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('pre_matric','govt_school','institution_type', '{"allow":["school"]}', 'warning',
   'Pre-Matric is administered through the school','प्री-मैट्रिक विद्यालय के माध्यम से',
   'https://tribal.nic.in/Scholarship.aspx'),

  ('post_matric','income_2_5lakh','income_ceiling', '{"maxAnnual":250000}', 'blocker',
   'Family income must not exceed Rs. 2.50 lakh per annum',
   'पारिवारिक आय वार्षिक Rs. 2.50 लाख से अधिक नहीं होनी चाहिए',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('post_matric','class_xi_plus','class_level', '{"min":"XI"}', 'blocker',
   'Student must be in Class XI or above','छात्र कक्षा XI या उससे ऊपर',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('post_matric','domicile_required','domicile', '{}', 'blocker',
   'Domicile certificate of the State / UT is required','आवासीय प्रमाण पत्र आवश्यक',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('post_matric','one_scheme_at_a_time','single_scheme', '{}', 'blocker',
   'A student may hold only one scholarship at a time','एक समय में केवल एक छात्रवृत्ति',
   'https://tribal.nic.in/Scholarship.aspx'),

  ('top_class','income_6lakh','income_ceiling', '{"maxAnnual":600000}', 'blocker',
   'Family income must not exceed Rs. 6.00 lakh per annum',
   'पारिवारिक आय वार्षिक Rs. 6.00 लाख से अधिक नहीं होनी चाहिए',
   'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf'),
  ('top_class','notified_institute','institution_flag', '{"flag":"is_top_class_institute"}', 'blocker',
   'Admission must be in a Ministry-notified Top Class Institute',
   'मंत्रालय द्वारा अधिसूचित टॉप क्लास संस्थान में प्रवेश आवश्यक',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('top_class','graduation_level','course_level', '{"allow":["graduation","post_graduation"]}', 'blocker',
   'Course must be Graduation or Post-Graduation','पाठ्यक्रम स्नातक या स्नातकोत्तर होना चाहिए',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('top_class','one_scheme_at_a_time','single_scheme', '{}', 'blocker',
   'A student may hold only one scholarship at a time','एक समय में केवल एक छात्रवृत्ति',
   'https://tribal.nic.in/Scholarship.aspx'),

  ('nfst','post_graduation_required','course_level', '{"allow":["m_phil","ph_d"]}', 'blocker',
   'Must be admitted to a regular, full-time M.Phil / Ph.D after a Post-Graduation degree',
   'स्नातकोत्तर उपाधि के बाद नियमित पूर्णकालिक M.Phil / Ph.D में प्रवेश आवश्यक',
   'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf'),
  ('nfst','ugc_entitled_institute','institution_flag', '{"flag":"is_nfst_host"}', 'blocker',
   'Institute must be UGC-entitled, Government-funded or an Institute of National Importance',
   'संस्थान UGC-योग्य या सरकार द्वारा वित्तपोषित होना चाहिए',
   'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf'),
  ('nfst','no_other_fellowship','single_scheme', '{"scope":"all"}', 'blocker',
   'NFST scholars cannot hold any other fellowship for the same study',
   'NFST छात्र उसी अध्ययन हेतु अन्य छात्रवृत्ति नहीं ले सकता',
   'https://www.ugc.gov.in/pdfnews/0242709_Revised-guidelines-of-NFSTS.pdf'),
  ('nfst','quarterly_review','percentile', '{"note":"Progressive quarterly review of research progress"}', 'info',
   'Fellowship is released quarterly after progress review','प्रगति की समीक्षा के बाद तिमाही जारी',
   'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf'),

  ('nos','income_6lakh','income_ceiling', '{"maxAnnual":600000}', 'blocker',
   'Family income must not exceed Rs. 6.00 lakh per annum',
   'पारिवारिक आय वार्षिक Rs. 6.00 लाख से अधिक नहीं होनी चाहिए',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('nos','qs_top_1000','qs_rank', '{"maxRank":1000}', 'blocker',
   'University must rank within the top 1000 in the latest QS World University Rankings',
   'विश्वविद्यालय QS वर्ल्ड यूनिवर्सिटी रैंकिंग में टॉप 1000 में होना चाहिए',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('nos','age_limit','age_limit', '{"masters":32,"phd":35,"postDoctoral":38}', 'blocker',
   'Age limit: 32 for Master''s, 35 for Ph.D, 38 for post-doctoral research',
   'आयु सीमा: मास्टर 32 वर्ष, पीएचडी 35 वर्ष, पोस्ट-डॉक्टोरल 38 वर्ष',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('nos','only_20_slots','seats_limit', '{"slots":20}', 'warning',
   'Only 20 awards are available every year across the country','प्रतिवर्ष केवल 20 पुरस्कार उपलब्ध',
   'https://tribal.nic.in/Scholarship.aspx'),
  ('nos','one_scheme_at_a_time','single_scheme', '{}', 'warning',
   'Concurrent scholarships must be surrendered before joining NOS',
   'NOS में शामिल होने से पूर्व अन्य छात्रवृत्ति वापस करनी होगी',
   'https://tribal.nic.in/Scholarship.aspx');

-- ---------- institutions ----------
insert into public.institutions
  (name, type, state_ut, district, affiliation, udise_plus, aishe_code, aishe_verified,
   is_top_class_institute, is_nfst_host, nos_eligible, qs_rank, naac_grade)
values
  ('Biju Patnaik Government High School, Rairakhol',        'school','Odisha',     'Sambalpur','government','21240300101', null, false, false, false, false, null, null),
  ('Kisan Science College, Bolangir',                        'college','Odisha',     'Balangir','government', null,'U-UNI-OD-1244', true, true, true, true, null,'A+'),
  ('Sambalpur University',                                   'university','Odisha',  'Sambalpur','government', null,'U-UNI-OD-0087', true, true, true, true, null,'A'),
  ('Nabarangpur College of Arts & Science',                  'college','Odisha',     'Nabarangpur','government', null,'U-COL-OD-0911', true, false, true, true, null,'B+'),
  ('Rani Durgavati Vishwavidyalaya',                         'university','Madhya Pradesh','Jabalpur','government', null,'U-UNI-MP-0042', true, true, true, true, null,'A'),
  ('Government College of Music, Bhopal',                    'college','Madhya Pradesh','Bhopal','government', null,'U-COL-MP-0533', true, true, true, true, null,'A'),
  ('Kasturba Gandhi Balika Vidyalaya, Dindori',              'school','Madhya Pradesh','Dindori','government','23210400307', null, false, false, false, false, null, null),
  ('Rajiv Gandhi University of Knowledge, Ranchi',           'university','Jharkhand','Ranchi',   'government', null,'U-UNI-JH-0021', true, true, true, true, null,'A'),
  ('St. Xavier's College, Ranchi',                           'college','Jharkhand',  'Ranchi',   'private',  null,'U-COL-JH-0233', true, true, true, true, null,'A+'),
  ('Tribal College of Education, Koraput',                   'college','Odisha',     'Koraput',  'government', null,'U-COL-OD-0788', true, false, true, true, null,'B'),
  ('Baba Bhimrao Ambedkar University, Unnao',               'university','Uttar Pradesh','Unnao','government', null,'U-UNI-UP-0177', true, true, true, true, null,'A'),
  ('University of Oxford (reference, NOS eligible)',        'university','Oxford','Oxford','deemed', null, null, true, false, true, true, 3, null);

-- ---------- integration registry ----------
insert into public.source_systems
  (code, name, category, base_url, auth_mode, env_key, mode, is_available, latency_ms, notes, sort_order)
values
  ('nsp',         'National Scholarship Portal',        'scholarship_portal','https://scholarships.gov.in',        'OIDC + captcha','SOURCE_NSP_TOKEN',        'mock', true,  320, 'Primary application intake for Pre-Matric, Post-Matric and Top Class.', 1),
  ('sfmp',        'Scholarship & Fellowship Management Portal (Canara Bank)','fellowship_portal','https://scholarship.canarabank.in','Aadhaar OTP','SOURCE_SFMP_TOKEN',     'mock', true,  410, 'NFST / UGC fellowship application and payment confirmation.', 2),
  ('nos_portal',  'National Overseas Scholarship Portal','scholarship_portal','https://nos.mota.gov.in',             'captcha','SOURCE_NOS_TOKEN',          'mock', true,  280, 'NOS applications, offer letters and sanction orders.', 3),
  ('mota',        'MoTA Scholarship & DBT',             'ministry_system','https://tribal.nic.in',                 'govt SSO','SOURCE_MOTA_TOKEN',        'mock', true,  260, 'Sanction orders and PFMS settlement summaries.', 4),
  ('digilocker',  'DigiLocker',                        'document_source','https://www.digilocker.gov.in',          'OAuth 2.0 / PKI','SOURCE_DIGILOCKER_CLIENT_ID','mock', true, 540, 'Issued document pull (Aadhaar, ST certificate, marksheet, income).', 5),
  ('uidai',       'UIDAI / Aadhaar (e-KYC)',           'identity_source','https://api.uidai.gov.in',            'OTP / offline e-KYC','SOURCE_UIDAI_KEY',     'mock', true,  610, 'Identity and Aadhaar-seeded bank status.', 6),
  ('edistrict',   'State e-District / revenue officer','certificate_source','https://edistrict.*.gov.in','Captcha + officer login','SOURCE_EDISTRICT_TOKEN','mock', true, 880, 'ST certificate, income certificate, domicile verification.', 7),
  ('udise_plus',  'UDISE+',                             'school_enrolment','https://udiseplus.gov.in',              'API key','SOURCE_UDISE_KEY',          'mock', true,  340, 'School enrolment and profile of classes IX–X students.', 8),
  ('aishe',       'AISHE',                              'higher_ed_enrolment','https://aishe.gov.in',               'API key','SOURCE_AISHE_KEY',         'mock', true,  360, 'Institute registration and sanctioned seat intake.', 9),
  ('apaar',       'APAAR / ABHAAR',                    'student_identity','https://www.apaar.education.gov.in',   'OAuth 2.0','SOURCE_APAAR_KEY',           'mock', true,  390, 'One Academic & One Aadhaar-mapped identifier for school students.', 10),
  ('otr',         'NSP OTR registry',                  'scholarship_portal','https://scholarships.gov.in',         'API key','SOURCE_NSP_TOKEN',           'mock', true,  240, 'One Time Registration presence — used for coverage-gap matching.', 11),
  ('ugc_nta',     'UGC-NTA',                            'qualification_source','https://www.nta.ac.in',            'API key','SOURCE_NTA_KEY',             'mock', true,  300, 'NET / JRF qualification and award letter.', 12),
  ('swavlamban',  'Swavlamban (UDID)',                  'disability_source','https://www.swavlamban.gov.in',     'API key','SOURCE_UDID_KEY',            'mock', true,  420, 'Disability certificate and UDID number.', 13),
  ('pfms',        'PFMS (Public Financial Management System)','payment_source','https://pfms.nic.in','govt SSO','SOURCE_PFMS_TOKEN','mock', true, 300, 'DBT batch, UTR and settlement status.', 14),
  ('qs',          'QS World University Rankings',       'reference_data','https://www.topuniversities.com',        'public','—',                           'mock', true,  200, 'Reference list for NOS eligibility (top 1000).', 15);

-- ---------- scripted scenarios for the demo / simulator ----------
insert into public.mock_overrides (connector, match_key, response, note)
values
  ('edistrict','income_certificate:PM-2025-778812', '{"valid":false,"reason":"expired","validTill":"2026-06-30","authority":"Sub-Divisional Officer, Balangir"}','Demo: expired income certificate → deficiency raised'),
  ('edistrict','st_certificate:ST-OD-2019-44120', '{"category":"ST","name":"Suriya Hansda","tribe":"Kondh","district":"Sambalpur","validTill":"2029-03-31","spellingVariant":"Suriya Hansdah"}','Demo: name spelling variant between student profile and ST certificate'),
  ('udise_plus','udise:21240300101', '{"enrolled":true,"class":"X","rollNo":"STU-2025-0042","apaarId":"APAAR-4412-9987"}','Demo: UDISE+ confirms enrolment in Class X'),
  ('aishe','aishe:U-COL-OD-1244', '{"verified":true,"isTopClass":true,"sanctionedSeats":50,"institutionName":"Kisan Science College, Bolangir"}','Demo: Top Class institute with 50 sanctioned seats'),
  ('ugc_nta','nta:NET-2024-77120', '{"qualified":true,"category":"JRF","year":2024,"validTill":"2026-12-31"}','Demo: NET/JRF qualified candidate'),
  ('qs','qs:university', '{"rank":3,"name":"University of Oxford","edition":"2026"}','Demo: QS reference list'),
  ('uidai','aadhaar:last4', '{"nameMatch":true,"dobMatch":true,"bankSeeded":true}', 'Demo: Aadhaar seeded bank'),
  ('pfms','pfms:RETURNED', '{"failureReason":"Aadhaar not seeded with bank account (NPCI mapper code 3054)"}','Demo: DBT return reason'),
  ('digilocker','digilocker:student', '{"documents":4,"issuer":"State Board of Secondary Education, Odisha","fetchMs":540}','Demo: DigiLocker pull returns 4 documents');

-- ---------- knowledge base (JAGO) ----------
insert into public.kb_articles (slug, category, title, body, tags, source_url)
values
  ('what-is-pre-matric', 'schemes',
   '{"en":"Pre-Matric Scholarship","hi":"प्री-मैट्रिक छात्रवृत्ति","sat":"ᱥᱟᱜᱚᱨᱟᱹ ᱠᱷᱟᱛᱚᱨᱛᱤ ᱠᱷᱩᱭᱟᱹᱨᱤᱭᱟᱹ","gon":"પ્રી-મેટ્રિક શિષ્યવૃત્તિ"}',
   '{"en":"Pre-Matric Scholarship for ST students covers Class IX and X. Parental income from all sources must not exceed Rs. 2.50 lakh per annum. Day scholars get Rs. 225 per month and hostellers Rs. 525 per month, for 10 months a year, paid by PFMS DBT into an Aadhaar-seeded bank account.",
     "hi":"ST छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति कक्षा IX और X के लिए है। सभी स्रोतों से माता-पिता की आय Rs. 2.50 लाख वार्षिक से अधिक नहीं होनी चाहिए। डे-स्कॉलर को Rs. 225 प्रति माह और छात्रावास को Rs. 525 प्रति माह, वर्ष में 10 माह मिलता है।",
     "sat":"ᱥᱟᱜᱚᱨᱟᱹ ᱠᱷᱟᱛᱚᱨᱛᱤ ᱠᱷᱩᱭᱟᱹᱨᱤᱭᱟᱹ ᱠᱞᱟᱥ IX ᱟᱨ X ᱠᱚᱞᱮᱭ ᱠᱟᱹ ᱥᱟᱜᱚᱨᱟᱹ ᱠᱷᱟᱛᱚᱨᱛᱤ ᱠᱷᱩᱭᱟᱹᱨᱤᱭᱟᱹ ᱟᱹᱫᱟᱹᱦᱤᱭ ᱢᱤᱡᱟᱹ ᱚᱲᱚᱭ ᱦᱩᱴᱤᱡ ᱠᱟᱹ ᱠᱚᱞᱟᱠᱚᱭ ᱢᱟᱹᱛᱷᱤᱭ ᱠᱚᱞᱮᱭ ᱮᱢᱟᱢ ᱞᱟᱸᱭᱤᱭ ᱫᱩᱭᱟᱠᱚᱭ ᱵᱟᱦᱟᱠ ᱦᱩᱴᱤᱡ ᱠᱟᱹ ᱠᱚᱞᱮᱭ ᱨᱮᱢᱟᱸᱨᱟᱚᱬᱟᱣ ᱵᱟᱝᱮᱞᱟ ᱠᱟᱹᱫᱟ ᱠᱟᱣᱡ ᱛᱩᱦᱚᱬᱟᱣ ᱠᱚᱭᱚᱫᱟᱚᱛᱟᱹ ᱠᱟᱹ ᱦᱩᱴᱤᱡ ᱨᱮᱢᱟᱸᱨᱟᱣ ᱵᱟᱝᱮᱞᱟ ᱠᱟᱱᱟᱫᱚᱫᱟ ᱠᱷᱤᱠᱚᱞ ᱠᱚᱞᱮᱭᱟᱹ ᱥᱟᱜᱩ ᱠᱚᱭᱩᱢᱤᱭᱟᱚᱬᱟᱣᱟᱹ ᱠᱚᱞᱮᱭᱟᱹ",
     "gon":"પ્રી-મેટ્રિક શિષ્યવૃત્તિમાં ST વિદ્યાર્થીઓ માટે ધોરણ IX અને X ના છે. માતાપિતાની વાર્ષિક આવક Rs. 2.50 લાખથી વધુ ન હોવી જોઈએ. દિવસી વિદ્યાર્થીને Rs. 225 અને હોસ્ટેલરને Rs. 525 દર માસ વર્ષના 10 માસ મળે છે."}'::jsonb,
   '{"schemes","pre_matric","income","hosteller"}', 'https://tribal.nic.in/Scholarship.aspx'),

  ('what-is-nfst', 'schemes',
   '{"en":"NFST Fellowship","hi":"NFST फेलोशिप","sat":"NFST ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ","kun":"NFST ᱜᱚᱲᱚᱛᱤ"}',
   '{"en":"The National Fellowship for Higher Education of ST Students supports M.Phil, M.Phil+Ph.D and Ph.D research. 750 fresh fellowships are given every year with no State or University ceiling. Stipend is Rs. 31,000 per month for M.Phil and for the first two Ph.D years, rising to Rs. 35,000 for the remaining years, plus contingency, HRA at UGC rates and an escort allowance of Rs. 2,000 for Divyangjan candidates. It is released quarterly through PFMS DBT.",
     "hi":"ST छात्रों के लिए राष्ट्रीय फेलोशिप M.Phil, M.Phil+Ph.D और Ph.D शोध को समर्थन देती है। प्रतिवर्ष 750 नए फेलोशिप दिए जाते हैं। M.Phil और पहले दो वर्षों के Ph.D के लिए मासिक वजीफा Rs. 31,000 है, शेष वर्षों में Rs. 35,000, साथ में कॉन्टिंजेंसी, UGC दर पर HRA और दिव्यांगज छात्रों के लिए Rs. 2,000 एस्कॉर्ट भत्ता।",
     "sat":"ᱥᱟᱜᱚᱨᱟᱹ ᱠᱷᱟᱛᱚᱨᱛᱤᱭᱟᱹᱠᱚᱱ ᱦᱩᱴᱤᱡ ᱥᱟᱜᱚᱨᱟᱹ ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ M.Phil, M.Phil+Ph.D ᱟᱨ Ph.D ᱥᱟᱢᱚᱫᱷ ᱠᱷᱚᱨ ᱮᱢ ᱦᱩᱥᱦᱤ ᱦᱮᱥ. ᱥᱟᱪᱟᱡ ᱮᱭᱟᱹ 750 ᱧᱩᱜ ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ ᱮᱢᱟᱠᱟᱫᱟᱣᱟᱫᱟ ᱠᱟᱣ. M.Phil ᱟᱨ Ph.D ᱨᱮᱟᱝ ᱮᱥᱟᱢ ᱵᱷᱟᱜ ᱮᱢᱟᱠᱚᱭ ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ ᱟᱹᱫᱟᱹᱦᱤᱭ ᱢᱤᱡᱟᱹ Rs. 31,000 ᱟᱨ ᱧᱩᱛᱟᱜ ᱮᱢᱟᱠᱚᱭ Rs. 35,000 ᱦᱩᱥᱦᱤᱡ ᱠᱷᱟᱝᱚᱷ ᱦᱩᱴᱤᱡ ᱠᱚᱞᱮᱭ ᱡᱚᱛᱚᱫᱚᱭ ᱠᱚᱭᱚᱫᱚᱛᱟᱹ ᱠᱚᱞᱮᱭᱟᱹ PFMS DBT ᱮᱢᱟᱠᱚᱭ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟᱫᱟᱣᱟᱫᱟ.",
     "kun":"NFST ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ ᱠᱷᱚᱨᱚ ᱠᱩᱵᱚᱨᱤᱭᱟᱹ ᱠᱟᱹ ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ M.Phil, M.Phil+Ph.D ᱟᱨ Ph.D ᱠᱚᱞᱮᱭ ᱠᱚᱞᱚᱭ ᱫᱩᱭᱟᱠ ᱠᱟᱹ. ᱥᱟᱪᱟᱡ ᱮᱭᱟᱹ 750 ᱧᱩᱜ ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ ᱮᱢᱟᱠᱟᱫᱟᱣᱟᱫᱟ ᱠᱟᱣ. M.Phil ᱟᱨ Ph.D ᱨᱮᱟᱝ ᱮᱥᱟᱢ ᱵᱷᱟᱜ ᱮᱢᱟᱠᱚᱭ Rs. 31,000 ᱟᱨ ᱧᱩᱛᱟᱜ ᱮᱢᱟᱠᱚᱭ Rs. 35,000 ᱢᱤᱡᱟᱹᱦᱩᱠᱩᱫᱟᱫᱟ, ᱠᱚᱞᱮᱭ ᱠᱟᱱᱟᱫᱟᱚᱫᱟ ᱠᱷᱟᱝᱚᱷ ᱠᱟᱹᱫᱟᱹᱦᱩ ᱥᱟᱮᱨᱠᱷᱟᱫᱚᱛᱟᱹ PFMS DBT ᱮᱢᱟᱠᱚᱭ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟᱫᱟᱣᱟᱫᱟ."}'::jsonb,
   '{"schemes","nfst","phd","stipend"}', 'https://scholarships.gov.in/public/schemeGuidelines/tribalfellowshipguideline.pdf'),

  ('one-scheme-at-a-time', 'rules',
   '{"en":"One scholarship at a time","hi":"एक समय में एक ही छात्रवृत्ति","sat":"ᱡᱚᱛᱚᱱ ᱚᱛᱚᱱ ᱠᱷᱟᱛᱚᱨᱛᱤ","ora":"ᱚᱛᱚᱱ ᱚᱛᱚᱱ ᱥᱠᱩᱞᱚᱨᱥᱚᱨᱥᱤᱯ"}',
   '{"en":"A student can hold only one scholarship or fellowship at a time. Before you apply for a new scheme, JagoScholarship shows the schemes you already hold, the income ceiling of the new scheme, and the documents that can be reused. If a new application is accepted, the earlier one must be surrendered.",
     "hi":"एक छात्र एक समय में केवल एक ही छात्रवृत्ति या फेलोशिप धारण कर सकता है। नई योजना के लिए आवेदन से पहले JagoScholarship दिखाता है कि आपके पास पहले से कौन-सी छात्रवृत्ति है, नई योजना की आय सीमा क्या है, और कौन से दस्तावेज दोबारा उपयोग हो सकते हैं। नया आवेदन स्वीकृत होने पर पुरानी छात्रवृत्ति वापस करनी होगी।",
     "sat":"ᱚᱛᱚᱱ ᱠᱷᱟᱛᱚᱨᱛᱤᱭᱟᱹ ᱚᱛᱚᱱ ᱚᱩᱴᱚᱛ ᱠᱷᱚᱨ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱟᱹ ᱜᱚᱲᱚᱛᱤ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟ ᱠᱟᱹᱫᱟᱹᱦᱤᱭ ᱠᱚᱞᱮᱭ ᱠᱟᱹᱫᱟᱹᱫᱚᱭᱦᱮᱞᱟ ᱵᱟᱝᱮᱞᱟ ᱠᱟᱹ ᱦᱤᱚᱱᱟᱹᱫᱚᱭᱟᱹ. ᱱᱟᱹᱛᱩ ᱵᱟᱝᱮᱞᱟ ᱨᱮᱢᱟᱠᱚᱭ JagoScholarship ᱧᱟᱹᱛᱩᱣᱟᱫᱟ ᱵᱟᱝᱮᱞᱟᱠᱟᱱᱟᱹ, ᱤᱱᱟᱜ ᱛᱤᱯᱚᱭ ᱠᱚᱞᱮᱭᱟᱹ ᱟᱨ ᱫᱩᱭᱟᱹᱦᱤᱭ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱭ ᱫᱩᱭᱟᱹᱦᱤᱭ ᱠᱟᱹ ᱧᱩᱭᱟᱹᱨᱤ ᱠᱟᱹ ᱠᱦᱩᱠᱚᱫᱚᱭᱟ ᱮᱢᱟᱠᱚᱭ ᱠᱟᱹ ᱵᱟᱝᱮᱞᱟᱫᱟ ᱠᱚᱫᱚᱛᱟ ᱠᱚᱞᱮᱭᱫᱟ.",
     "ora":"ᱚᱛᱚᱱ ᱥᱴᱩᱰᱮᱱᱛ ᱚᱛᱚᱱ ᱥᱠᱩᱞᱚᱨᱥᱚᱨᱥᱤᱯ ᱨᱮ ᱜᱚᱲᱚᱛᱤ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱟᱹ ᱢᱩᱛᱟᱠᱟᱹ ᱠᱟᱹᱫᱚᱭᱟᱹᱫᱟ ᱠᱚᱞᱮᱭᱟᱫᱟ. ᱱᱟᱹᱛᱩ ᱵᱟᱝᱮᱞᱟ ᱨᱮᱢᱟᱠᱚᱭ JagoScholarship ᱧᱟᱹᱛᱩᱣᱟᱫᱟ ᱚᱱᱟᱱ ᱠᱷᱟᱛᱚᱨᱛᱤ, ᱤᱱᱟᱜ ᱛᱤᱯᱚᱭ ᱠᱚᱞᱮᱭᱟᱹ ᱟᱨ ᱫᱩᱭᱟᱹᱦᱤᱭ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱭ ᱫᱩᱭᱟᱹᱦᱤᱭ ᱠᱟᱹ ᱠᱦᱩᱠᱚᱫᱚᱭᱟ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟ ᱠᱟᱹ ᱵᱟᱝᱮᱞᱟᱫᱟ ᱠᱚᱫᱚᱛᱟ ᱠᱚᱞᱮᱭᱫᱟ."}'::jsonb,
   '{"rules","concurrency","one_scheme"}', 'https://tribal.nic.in/Scholarship.aspx'),

  ('what-documents', 'documents',
   '{"en":"Which documents do I need?","hi":"कौन से दस्तावेज चाहिए?","sat":"ᱠᱚᱛᱚ ᱡᱚᱠᱚᱛᱚ ᱫᱩᱡᱟᱹ?","kui":"ᱚᱠᱚᱭᱚᱨ ᱡᱚᱠᱚᱛᱚᱨᱚᱨᱚ ᱫᱩᱡᱚᱫᱚ?"}',
   '{"en":"All schemes need your ST certificate, Aadhaar, income certificate, and an Aadhaar-seeded bank account. Post-Matric and Top Class also need your previous marksheet. NFST needs your post-graduation marksheet and institute confirmation. NOS needs a valid passport, a university offer letter, and QS ranking evidence. If a document is already in your wallet or available on DigiLocker, JagoScholarship reuses it instead of asking you to upload again.",
     "hi":"सभी योजनाओं के लिए ST प्रमाण पत्र, आधार, आय प्रमाण पत्र और आधार से जुड़ा बैंक खाता चाहिए। पोस्ट-मैट्रिक और टॉप क्लास के लिए पिछली मार्कशीट भी चाहिए। NFST के लिए स्नातकोत्तर मार्कशीट और संस्थान की पुष्टि चाहिए। NOS के लिए वैध पासपोर्ट, विश्वविद्यालय का ऑफर लेटर और QS रैंकिंग प्रमाण चाहिए। यदि दस्तावेज वॉलेट में या डिजिलॉकर में पहले से मौजूद है, तो JagoScholarship उसे दोबारा उपयोग करता है।",
     "sat":"ᱡᱚᱛᱚ ᱥᱠᱢᱤᱭ ᱠᱟᱹ ᱟᱵᱚᱫ ᱠᱷᱟᱛᱚᱨᱛᱤ ᱠᱟᱹᱵᱤᱠᱤᱡ, ᱟᱜᱚᱪᱟᱨ, ᱢᱤᱡᱟᱹ ᱠᱟᱹᱢᱤᱡ ᱤᱠᱚᱡᱟᱨᱟ ᱵᱟᱝᱮᱞᱟ ᱦᱤᱥᱥᱚᱱ ᱠᱟᱹ ᱮᱢ ᱫᱩᱭᱟᱹ ᱠᱚᱭ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱞᱮᱭ ᱦᱤᱥᱦᱤᱡ ᱦᱩᱥᱦᱤᱡ ᱮᱢᱟᱠᱚᱭ ᱠᱟᱹ ᱠᱦᱩᱠᱚᱫᱚᱭᱟ ᱠᱟᱹᱫᱚᱭᱟᱹᱫᱟ. ᱯᱚᱥᱴ-ᱢᱮᱴᱨᱤᱠ ᱟᱨ ᱴᱚᱯ ᱠᱞᱟᱥ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱮ ᱢᱟᱨᱠᱥᱚᱴᱥᱚᱴ ᱠᱟᱹ ᱫᱩᱡᱟᱫᱟ ᱠᱟᱣ. ᱡᱚᱛᱚᱱ ᱡᱚᱠᱚᱛᱚ ᱣᱚᱞᱮᱴ ᱨᱮ ᱫᱩᱢᱤ ᱠᱚᱞᱮᱭ ᱨᱮ ᱟᱹᱫᱟᱹᱫᱚᱭᱟᱹᱫᱟᱫᱟ ᱮᱢᱟᱠᱚᱭ, JagoScholarship ᱮᱢᱢᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱭ ᱨᱤᱥᱟᱮ ᱵᱟᱝᱮᱞᱟ ᱠᱟᱹ ᱵᱟᱝᱮᱞᱟ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟ ᱠᱚᱭᱚᱫᱚᱭᱟ.",
     "kui":"ᱡᱚᱛᱚ ᱥᱠᱢᱤᱭ ᱠᱟᱹ ᱟᱵᱚᱫ ᱠᱷᱟᱛᱚᱨᱛᱤ ᱠᱟᱹᱵᱤᱠᱤᱡ, ᱟᱜᱚᱪᱟᱨ, ᱢᱤᱜᱚᱭ ᱠᱟᱹᱢᱤᱡ ᱤᱠᱚᱡᱟᱨᱟ ᱵᱟᱝᱮᱞᱟ ᱦᱤᱥᱥᱚᱱ ᱠᱟᱹ ᱢᱩᱛᱟᱠᱟᱹ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱞᱮᱭ ᱦᱤᱥᱦᱤᱡ ᱦᱩᱥᱦᱤᱡ ᱮᱢᱟᱠᱚᱭ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱞᱮᱭ ᱦᱤᱥᱦᱤᱡ ᱦᱩᱥᱦᱤᱡ ᱮᱢᱟᱠᱚᱭ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱞᱮᱭ ᱠᱟᱹ ᱵᱟᱝᱮᱞᱟ. ᱯᱚᱥᱴ-ᱢᱮᱴᱨᱤᱠ ᱟᱨ ᱴᱚᱯ ᱠᱞᱟᱥ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱟᱹ ᱢᱟᱨᱠᱥ ᱥᱤᱧᱴ ᱠᱚᱭ ᱫᱩᱡᱟᱫᱟ. NFST ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱟᱹ ᱥᱢᱟᱝᱚᱛᱟᱹᱴᱤᱡ ᱢᱟᱨᱠᱥ ᱥᱤᱧᱴ ᱟᱨ ᱥᱤᱦᱩᱜᱟᱱᱚ ᱢᱟᱝᱟ ᱠᱟᱹᱫᱚᱭᱚᱫᱚ. NOS ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱟᱹ ᱥᱤᱛᱟᱹᱣᱟᱜ ᱯᱚᱥᱯᱚᱨᱴ, ᱤᱱᱟᱜ ᱩᱱᱤᱣᱚᱨᱥᱤᱴᱤ ᱚᱵᱚᱨ ᱞᱮᱴᱚᱨ ᱟᱨ QS ᱨᱮᱝᱠ ᱯᱨᱮᱢᱟᱣ ᱠᱟᱹᱫᱚᱭᱚᱫᱚ. ᱡᱚᱠᱚᱛᱚ ᱣᱚᱞᱮᱴ ᱨᱮ ᱫᱩᱢᱤ ᱨᱤᱥᱚᱫᱚᱭᱟᱫᱚᱭᱟ ᱠᱚᱞᱚᱫᱚᱭᱟ, JagoScholarship ᱮᱢᱢᱟᱹ ᱵᱟᱝᱮᱞᱟ ᱨᱤᱥᱟᱮ ᱵᱟᱝᱮᱞᱟ ᱠᱟᱹ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟ ᱠᱚᱭᱚᱫᱚᱭᱟ."}'::jsonb,
   '{"documents","digilocker","reuse"}', 'https://tribal.nic.in/Scholarship.aspx'),

  ('payment-timetable', 'payments',
   '{"en":"When will I get the money?","hi":"पैसा कब मिलेगा?","sat":"ᱠᱟᱹᱛᱚ ᱥᱟᱫᱟᱠᱟᱢ ᱢᱤᱞᱟᱫ?","gon":"ક્યારે પૈસા મળશે?"}',
   '{"en":"Pre-Matric and Post-Matric amounts are credited month by month after the State forwards the proposal. Top Class stipend and books are released to you by PFMS DBT while tuition goes to the institute. NFST fellowship is released quarterly after a progress review. NOS is released in instalments tied to your offer letter and joining. If a payment is returned, the reason appears against the instalment and JagoScholarship tells you exactly what to fix at your bank.",
     "hi":"प्री-मैट्रिक और पोस्ट-मैट्रिक की राशि राज्य द्वारा प्रस्ताव भेजने के बाद मासिक जारी होती है। टॉप क्लास का वजीफा और किताबों की राशि PFMS DBT से आपको मिलती है जबकि ट्यूशन फीस संस्थान को जाती है। NFST फेलोशिप प्रगति समीक्षा के बाद तिमाही जारी होती है। NOS आपके ऑफर लेटर और प्रवेश के आधार पर किस्तों में जारी होती है। यदि भुगतान वापस आता है, तो किस्त के सामने कारण दिखता है और JagoScholarship बताता है कि बैंक में क्या ठीक करना है।",
     "sat":"ᱯᱨᱤ-ᱢᱮᱴᱨᱤᱠ ᱟᱨ ᱯᱚᱥᱴ-ᱢᱮᱴᱨᱤᱠ ᱨᱮᱟᱝ ᱫᱩᱢᱚᱛ ᱟᱦᱚᱱᱚᱫᱚᱛ ᱢᱩᱴᱟᱛ ᱮᱢᱟᱠᱚᱭ ᱵᱟᱣᱫᱚᱭ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟ ᱦᱩᱥᱦᱤᱡ ᱦᱩᱥᱦᱤᱡ ᱠᱚᱞᱮᱭ ᱠᱟᱹ ᱮ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟᱫᱚᱭ ᱠᱚᱞᱮᱭᱟᱹᱫᱟ. ᱴᱚᱯ ᱠᱞᱟᱥ ᱨᱮᱟᱝ PFMS DBT ᱮᱢᱟᱠᱚᱭ ᱟᱵᱚᱫᱤᱠᱟᱹ ᱠᱚᱞᱮᱭᱟ ᱮᱢᱟᱠᱚᱭ ᱟᱜᱚᱪᱟᱨ ᱵᱟᱝᱮᱞᱟ ᱠᱚᱞᱚᱭ ᱦᱩᱥᱦᱤᱡᱭᱟᱝᱟᱫᱚᱭ ᱠᱟᱹᱫᱟᱝᱟ. NFST ᱨᱤᱥᱤᱭᱟᱹᱨᱤᱭᱟᱹ ᱠᱷᱚᱨ ᱥᱟᱫᱟᱠᱟᱢ ᱧᱩᱫᱚᱭ ᱮᱢᱟᱠᱚᱭ ᱤᱢᱚᱵᱚᱡᱩ ᱠᱚᱞᱮᱭᱟᱹ ᱠᱚᱞᱚᱫᱚᱫᱚᱛᱟᱹ. ᱡᱚᱛᱚᱱ ᱠᱟᱹ ᱧᱩᱭᱟᱹ ᱠᱚᱭ ᱨᱮ ᱮᱢᱟᱠᱚᱭ ᱮᱛᱟᱝᱚᱫᱚᱭᱟ ᱠᱚᱨᱵᱚᱨᱟ ᱠᱚᱞᱮᱭᱟᱹ ᱠᱚᱞᱚᱫᱚᱛᱟᱹ JagoScholarship ᱠᱚᱭ ᱥᱤᱛᱚᱨᱤᱡᱭᱟᱣᱟᱫᱟ ᱵᱢᱮᱨᱟ ᱠᱚᱞᱮᱭᱟᱹ ᱠᱟᱹ ᱠᱚᱞᱚᱰᱚᱣᱫ ᱠᱟᱹ ᱠᱚᱣ ᱠᱚᱞᱮᱭᱫᱚᱭᱟ ᱠᱟᱹ ᱵᱟᱝᱮᱞᱟᱫᱚ.",
     "gon":"પ્રી-મેટ્રિક અને પોસ્ટ-મેટ્રિકની રકમ રાજ્ય દ્વારા દરજ્જો મોકલાય પછી દર મહિને મળે છે. ટોપ ક્લાસનું વજીફું અને પુસ્તકોની રકમ PFMS DBT થી તમને મળે છે અને ટ્યુશન ફી સંસ્થાને જાય છે. NFST ફેलोશિપ પ્રગતિ સમીક્ષા પછી ત્રિમાસિક આવે છે. ચૂકવણી પાછી આવે તો કારણ સામે દેખાય છે."}'::jsonb,
   '{"payments","dbt","pfms"}', 'https://tribal.nic.in/Scholarship.aspx');
